services:
  db:
    image: postgres:18.1
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      LC_COLLATE: C.UTF-8
      LC_CTYPE: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql
